
---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:dev;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  
---

spring:
  profiles: integration
  datasource:
    url: jdbc:h2:mem:integrationdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
